### ISSUE TITLE
Multiple Handlers

### ISSUE THREAD

**Issue by damogallagher** [ccampo133/spring-aws-lambda#1]
Hi

Can this approach allow for an application to have multiple Lambda handlers implemented in the same project?

Thanks
Damien

**Comment by ccampo133** [comment]
Hi Damien

Currently, AWS allows one handler per Lambda function. This serves as the entry point to your application. It doesn't make much sense to have more than one handler in a single Lambda function. If you register more than one bean of type `RequestHandler`, Spring will throw a `NoUniqueBeanDefinitionException` (see: [Spring's docs](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/BeanFactory.html#getBean-java.lang.Class-)). So to answer your question plainly, no.

My advice is, if you want to handle multiple types of events on the same Lambda function, would be to create a generic handler that exposes the raw byte streams (e.g. by implementing [SpringRequestStreamHandler](https://github.com/ccampo133/spring-aws-lambda/blob/master/spring-aws-lambda/src/main/java/me/ccampo/spring/aws/lambda/SpringRequestStreamHandler.java) and registering it as a bean) and then handle your deserialization and routing logic there.

**Comment by damogallagher** [comment]
Hi Chris

Thanks this makes alot of sense and it was working for me
Was wondering if you could help me with another question which I have posted on Stackoverflow?http://stackoverflow.com/questions/43101999/deploy-spring-boot-application-on-amazon-lambda

Thanks for your time
Damien

**Comment by ccampo133** [comment]
Sorry, I've not used Spring Boot with Lambda yet.

**Comment by damogallagher** [comment]
No worries - thank you
